CREATE DATABASE IF NOT EXISTS backend;
USE backend;

CREATE TABLE IF NOT EXISTS users (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  username VARCHAR(255) NOT NULL,
  password VARCHAR(45) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS todo (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  completed BOOLEAN DEFAULT false,
  user_id UNIQUEIDENTIFIER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);