services: 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "9999:9999"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.2GB"
  
  api: 
    build: .
    hostname: backend_gg
    restart: on-failure
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge
    name: backend_gg
